name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install UPX
        run: sudo apt update && sudo apt install upx just
      - name: Build
        run: just build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.exe
          token: ${{ secrets.TOKEN_GITHUB }}
