name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install UPX
        run: sudo apt update && sudo apt install upx just
      - name: Build
        run: just package-linux
      - name: Generate sha
        run: go version
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.tar.gz
          token: ${{ secrets.TOKEN_GITHUB }}
